// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using academia.Data;

#nullable disable

namespace academia.Migrations
{
    [DbContext(typeof(AcademiaContext))]
    partial class AcademiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("academia.Models.Asistencia", b =>
                {
                    b.Property<int>("IdAsist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_asist");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsist"));

                    b.Property<string>("EstadoAsis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_asis");

                    b.Property<DateTime>("FechaAsis")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asis");

                    b.Property<int>("IdClase")
                        .HasColumnType("integer")
                        .HasColumnName("id_clase");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("integer")
                        .HasColumnName("id_estudiante");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int?>("RegistradaPor")
                        .HasColumnType("integer")
                        .HasColumnName("registrada_por");

                    b.HasKey("IdAsist")
                        .HasName("pk_asistencia");

                    b.HasIndex("IdClase")
                        .HasDatabaseName("ix_asistencia_id_clase");

                    b.HasIndex("IdEstudiante")
                        .HasDatabaseName("ix_asistencia_id_estudiante");

                    b.HasIndex("RegistradaPor")
                        .HasDatabaseName("ix_asistencia_registrada_por");

                    b.ToTable("asistencia", (string)null);
                });

            modelBuilder.Entity("academia.Models.AuditLog", b =>
                {
                    b.Property<long>("IdAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_audit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdAudit"));

                    b.Property<string>("CamposModificados")
                        .HasColumnType("jsonb")
                        .HasColumnName("campos_modificados");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_anteriores");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_nuevos");

                    b.Property<long?>("DuracionMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duracion_ms");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("endpoint");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean")
                        .HasColumnName("exitoso");

                    b.Property<DateTime>("FechaOperacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_operacion");

                    b.Property<string>("IdRegistro")
                        .HasColumnType("text")
                        .HasColumnName("id_registro");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MensajeError")
                        .HasColumnType("text")
                        .HasColumnName("mensaje_error");

                    b.Property<string>("MetodoHttp")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("metodo_http");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("RolUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol_usuario");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tabla_afectada");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_operacion");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("IdAudit")
                        .HasName("pk_audit_log");

                    b.HasIndex("FechaOperacion")
                        .HasDatabaseName("ix_audit_log_fecha_operacion");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_audit_log_id_usuario");

                    b.HasIndex("TablaAfectada")
                        .HasDatabaseName("ix_audit_log_tabla_afectada");

                    b.HasIndex("TablaAfectada", "IdRegistro")
                        .HasDatabaseName("ix_audit_log_tabla_afectada_id_registro");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("academia.Models.Clase", b =>
                {
                    b.Property<int>("IdClase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_clase");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClase"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<int>("CapacidadMax")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_max");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dia_semana");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("interval")
                        .HasColumnName("hora");

                    b.Property<int>("IdEstilo")
                        .HasColumnType("integer")
                        .HasColumnName("id_estilo");

                    b.Property<int>("IdProfesor")
                        .HasColumnType("integer")
                        .HasColumnName("id_profesor");

                    b.Property<string>("NombreClase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_clase");

                    b.Property<decimal>("PrecioMensuClas")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_mensu_clas");

                    b.HasKey("IdClase")
                        .HasName("pk_clase");

                    b.HasIndex("IdEstilo")
                        .HasDatabaseName("ix_clase_id_estilo");

                    b.HasIndex("IdProfesor")
                        .HasDatabaseName("ix_clase_id_profesor");

                    b.ToTable("clase", (string)null);
                });

            modelBuilder.Entity("academia.Models.Cobro", b =>
                {
                    b.Property<int>("IdCobro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cobro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCobro"));

                    b.Property<int?>("AnioCorrespondiente")
                        .HasColumnType("integer")
                        .HasColumnName("anio_correspondiente");

                    b.Property<string>("EstadoCobro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_cobro");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("integer")
                        .HasColumnName("id_estudiante");

                    b.Property<string>("MesCorrespondiente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mes_correspondiente");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("text")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("TipoCobro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_cobro");

                    b.HasKey("IdCobro")
                        .HasName("pk_cobro");

                    b.HasIndex("IdEstudiante")
                        .HasDatabaseName("ix_cobro_id_estudiante");

                    b.ToTable("cobro", (string)null);
                });

            modelBuilder.Entity("academia.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    b.Property<bool>("NoAsisto")
                        .HasColumnType("boolean")
                        .HasColumnName("no_asisto");

                    b.Property<bool>("Retirado")
                        .HasColumnType("boolean")
                        .HasColumnName("retirado");

                    b.HasKey("IdEstado")
                        .HasName("pk_estado");

                    b.HasIndex("IdPersona")
                        .HasDatabaseName("ix_estado_id_persona");

                    b.ToTable("estado", (string)null);
                });

            modelBuilder.Entity("academia.Models.EstiloDanza", b =>
                {
                    b.Property<int>("IdEstilo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estilo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstilo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("EdadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("edad_maxima");

                    b.Property<int?>("EdadMinima")
                        .HasColumnType("integer")
                        .HasColumnName("edad_minima");

                    b.Property<string>("NivelDificultad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel_dificultad");

                    b.Property<string>("NombreEsti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_esti");

                    b.Property<decimal?>("PrecioBase")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_base");

                    b.HasKey("IdEstilo")
                        .HasName("pk_estilo_danza");

                    b.ToTable("estilo_danza", (string)null);
                });

            modelBuilder.Entity("academia.Models.Inscripcion", b =>
                {
                    b.Property<int>("IdInsc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_insc");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInsc"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime>("FechaInsc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_insc");

                    b.Property<int>("IdClase")
                        .HasColumnType("integer")
                        .HasColumnName("id_clase");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("integer")
                        .HasColumnName("id_estudiante");

                    b.Property<string>("MotivoBaja")
                        .HasColumnType("text")
                        .HasColumnName("motivo_baja");

                    b.HasKey("IdInsc")
                        .HasName("pk_inscripcion");

                    b.HasIndex("IdClase")
                        .HasDatabaseName("ix_inscripcion_id_clase");

                    b.HasIndex("IdEstudiante")
                        .HasDatabaseName("ix_inscripcion_id_estudiante");

                    b.ToTable("inscripcion", (string)null);
                });

            modelBuilder.Entity("academia.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_persona");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersona"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cedula");

                    b.Property<string>("CondicionesMedicas")
                        .HasColumnType("text")
                        .HasColumnName("condiciones_medicas");

                    b.Property<string>("Contrasena")
                        .HasColumnType("text")
                        .HasColumnName("contrasena");

                    b.Property<string>("Correo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Especialidad")
                        .HasColumnType("text")
                        .HasColumnName("especialidad");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime?>("FechaContrato")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_contrato");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Genero")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("genero");

                    b.Property<int?>("IdEstudianteRepresentado")
                        .HasColumnType("integer")
                        .HasColumnName("id_estudiante_representado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Parentesco")
                        .HasColumnType("text")
                        .HasColumnName("parentesco");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol");

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnType("numeric")
                        .HasColumnName("salario_base");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("IdPersona")
                        .HasName("pk_persona");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_persona_correo");

                    b.HasIndex("IdEstudianteRepresentado")
                        .HasDatabaseName("ix_persona_id_estudiante_representado");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("academia.Models.Asistencia", b =>
                {
                    b.HasOne("academia.Models.Clase", "Clase")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdClase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asistencia_clase_id_clase");

                    b.HasOne("academia.Models.Persona", "Estudiante")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asistencia_persona_id_estudiante");

                    b.HasOne("academia.Models.Persona", "RegistradaPorPersona")
                        .WithMany()
                        .HasForeignKey("RegistradaPor")
                        .HasConstraintName("fk_asistencia_persona_registrada_por");

                    b.Navigation("Clase");

                    b.Navigation("Estudiante");

                    b.Navigation("RegistradaPorPersona");
                });

            modelBuilder.Entity("academia.Models.Clase", b =>
                {
                    b.HasOne("academia.Models.EstiloDanza", "EstiloDanza")
                        .WithMany("Clases")
                        .HasForeignKey("IdEstilo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_clase_estilo_danza_id_estilo");

                    b.HasOne("academia.Models.Persona", "Profesor")
                        .WithMany("ClasesImpartidas")
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_clase_persona_id_profesor");

                    b.Navigation("EstiloDanza");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("academia.Models.Cobro", b =>
                {
                    b.HasOne("academia.Models.Persona", "Estudiante")
                        .WithMany("Cobros")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cobro_persona_id_estudiante");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("academia.Models.Estado", b =>
                {
                    b.HasOne("academia.Models.Persona", "Persona")
                        .WithMany("Estados")
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_estado_persona_id_persona");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("academia.Models.Inscripcion", b =>
                {
                    b.HasOne("academia.Models.Clase", "Clase")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdClase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inscripcion_clase_id_clase");

                    b.HasOne("academia.Models.Persona", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inscripcion_persona_id_estudiante");

                    b.Navigation("Clase");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("academia.Models.Persona", b =>
                {
                    b.HasOne("academia.Models.Persona", "EstudianteRepresentado")
                        .WithMany("Representantes")
                        .HasForeignKey("IdEstudianteRepresentado")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_persona_persona_id_estudiante_representado");

                    b.Navigation("EstudianteRepresentado");
                });

            modelBuilder.Entity("academia.Models.Clase", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("academia.Models.EstiloDanza", b =>
                {
                    b.Navigation("Clases");
                });

            modelBuilder.Entity("academia.Models.Persona", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("ClasesImpartidas");

                    b.Navigation("Cobros");

                    b.Navigation("Estados");

                    b.Navigation("Inscripciones");

                    b.Navigation("Representantes");
                });
#pragma warning restore 612, 618
        }
    }
}
